name: Nightly Publish Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false

jobs:
  Publish:
    name: Nightly Publish
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      cache-assets: true
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      MavenSettings: ${{ secrets.MAVEN_SETTINGS }}
      JavaGpgKeyPassphrase: ${{ secrets.JAVA_GPG_KEY_PASSPHRASE }}
      JavaPGP: ${{ secrets.JAVA_KEY_PGP_FILE }}
      CodeSigningKeyVaultName: ${{ secrets.CODE_SIGNING_KEY_VAULT_NAME }}
      CodeSigningKeyVaultUrl: ${{ secrets.CODE_SIGNING_KEY_VAULT_URL }}
      CodeSigningKeyVaultClientId: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_ID }}
      CodeSigningKeyVaultTenantId: ${{ secrets.CODE_SIGNING_KEY_VAULT_TENANT_ID }}
      CodeSigningKeyVaultClientSecret: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_SECRET }}
      CodeSigningKeyVaultCertificateName: ${{ secrets.CODE_SIGNING_KEY_VAULT_CERTIFICATE_NAME }}
      CodeSigningKeyVaultCertificateData: ${{ secrets.CODE_SIGNING_KEY_VAULT_CERTIFICATE_DATA }}
